import { AppSettings } from "./types";

export const DEFAULT_SETTINGS: AppSettings = {
  binance: {
    apiKey: import.meta.env.VITE_BINANCE_API_KEY || "oDQleHC2fKUyLORiNvYxDhbjMwd0tSJerZ16UpDeodVpftUt5rajHDac8f0qhPZX",
    secretKey: import.meta.env.VITE_BINANCE_SECRET_KEY || "APwIfMbrtqw3oo0Xi3xmm4JgyXepOI1m0GVAurggIyw0VWJ1hWU0QpXJ3e7Yxoes",
    baseUrl: import.meta.env.VITE_BINANCE_BASE_URL || "https://fapi.binance.com",
    wsUrl: import.meta.env.VITE_BINANCE_WS_URL || "wss://fstream.binance.com/ws",
  },
  supabase: {
    projectUrl: "https://lrhuayeivfmrvoiguszs.supabase.co",
    publishableKey: "sb_publishable_NRT27EsefJyCTaP8x1x1sQ_hVLrlK8f",
    connectionString: "postgresql://postgres:TwgdhFlzx3qc@db.lrhuayeivfmrvoiguszs.supabase.co:5432/postgres",
    supaName: "supa01",
  },
  scanner: {
    stage0Period: "1h",
    stage0StartTime: "38:39",
    stage0KLineInterval: "15m",
    stage0KCountMin: 500,
    stage0KCountMax: 15000,
    stage0CustomMinutes: 15,
    
    stage0PEnabled: true,
    stage0PPeriod: "15m",
    stage0PStartTime: "05:20",
    stage0P15mEnabled: true,
    stage0P15mCount: 4,
    stage0P15mRef: 3,
    stage0P1hEnabled: false,
    stage0P1hCount: 4,
    stage0P1hRef: 0,
    stage0P4hEnabled: false,
    stage0P4hCount: 6,
    stage0P4hRef: 0,
    stage0PDayEnabled: false,
    stage0PDayCount: 1,
    stage0PDayRef: 0,
    stage0PParam1Enabled: false,
    stage0PParam1Ref: 0,
    stage0PParam2Enabled: false,
    stage0PParam2Ref: 0,
    stage0PParam3Enabled: false,
    stage0PParam3Ref: 0,

    stage1Period: "15m",
    stage1StartTime: "00:14:40.123",
    stage1MinVolume: 1000000,
    stage1KLineMin: 0,
    stage1KLineMax: 10,
    whitelist: "",
    blacklist: "",
    stage1Cond1Enabled: true,
    stage1Cond2Enabled: true,

    stage2K21: 1,
    stage2K22: 8,
    stage2A21: 0,
    stage2A22: 10,
    stage2M21: 2000000,
    stage2M22: 100000000,
    stage2K51: 0,
    stage2K52: 4,
    stage2KB1: 0,
    stage2KB2: 2,
    stage2Period: "15m",
    stage2StartTime: "00:14:57.123",
    stage2Cooldown: 0,
    stage2Cond1Enabled: true,
    stage2Cond2Enabled: false,
    stage2Cond3Enabled: false,
    stage2Cond4Enabled: false,
    stage2Cond5Enabled: false,
  },
  order: {
    leverage: 5,
    positionRatio: 0.5,
    maxPositionAmount: 20,
    takeProfitRatio: 5,
    stopLossRatio: 5,
    forwardOrderWindow: 3,
    maxHoldTime: 100000,
    period: "15m",
    startTime: "00:14:59.400",
    kClosedPeriod: "15m",
    kClosedWindowStart: 1,
    kClosedWindowEnd: 4,
  },
  lockPassword: "Flzx3qc",
  lockTimeout: 60,
  masterSwitch: true,
  ipSelection: 'proxy',
  email: {
    enabled: false,
    from: "yyb_cq@hotmail.com",
    to: "yyb_cq@163.com",
    smtp: "smtp.live.com",
    port: 587,
    pass: "",
    balanceLimitEnabled: false,
    balanceLimit: 10000,
    reverseOrderLimitEnabled: false,
    reverseOrderLimit: 3,
  },
};
